//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamofMillions.MemberService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberService.DreamsWebServiceSoap")]
    public interface DreamsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name FName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserAddorEdit", ReplyAction="*")]
        DreamofMillions.MemberService.UserAddorEditResponse UserAddorEdit(DreamofMillions.MemberService.UserAddorEditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserAddorEdit", ReplyAction="*")]
        System.Threading.Tasks.Task<DreamofMillions.MemberService.UserAddorEditResponse> UserAddorEditAsync(DreamofMillions.MemberService.UserAddorEditRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAddorEditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserAddorEdit", Namespace="http://tempuri.org/", Order=0)]
        public DreamofMillions.MemberService.UserAddorEditRequestBody Body;
        
        public UserAddorEditRequest() {
        }
        
        public UserAddorEditRequest(DreamofMillions.MemberService.UserAddorEditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAddorEditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password;
        
        public UserAddorEditRequestBody() {
        }
        
        public UserAddorEditRequestBody(string FName, string LName, string UserName, string EmailAddress, string Password) {
            this.FName = FName;
            this.LName = LName;
            this.UserName = UserName;
            this.EmailAddress = EmailAddress;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAddorEditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserAddorEditResponse", Namespace="http://tempuri.org/", Order=0)]
        public DreamofMillions.MemberService.UserAddorEditResponseBody Body;
        
        public UserAddorEditResponse() {
        }
        
        public UserAddorEditResponse(DreamofMillions.MemberService.UserAddorEditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAddorEditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserAddorEditResult;
        
        public UserAddorEditResponseBody() {
        }
        
        public UserAddorEditResponseBody(int UserAddorEditResult) {
            this.UserAddorEditResult = UserAddorEditResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DreamsWebServiceSoapChannel : DreamofMillions.MemberService.DreamsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DreamsWebServiceSoapClient : System.ServiceModel.ClientBase<DreamofMillions.MemberService.DreamsWebServiceSoap>, DreamofMillions.MemberService.DreamsWebServiceSoap {
        
        public DreamsWebServiceSoapClient() {
        }
        
        public DreamsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DreamsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DreamsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DreamsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DreamofMillions.MemberService.UserAddorEditResponse DreamofMillions.MemberService.DreamsWebServiceSoap.UserAddorEdit(DreamofMillions.MemberService.UserAddorEditRequest request) {
            return base.Channel.UserAddorEdit(request);
        }
        
        public int UserAddorEdit(string FName, string LName, string UserName, string EmailAddress, string Password) {
            DreamofMillions.MemberService.UserAddorEditRequest inValue = new DreamofMillions.MemberService.UserAddorEditRequest();
            inValue.Body = new DreamofMillions.MemberService.UserAddorEditRequestBody();
            inValue.Body.FName = FName;
            inValue.Body.LName = LName;
            inValue.Body.UserName = UserName;
            inValue.Body.EmailAddress = EmailAddress;
            inValue.Body.Password = Password;
            DreamofMillions.MemberService.UserAddorEditResponse retVal = ((DreamofMillions.MemberService.DreamsWebServiceSoap)(this)).UserAddorEdit(inValue);
            return retVal.Body.UserAddorEditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DreamofMillions.MemberService.UserAddorEditResponse> DreamofMillions.MemberService.DreamsWebServiceSoap.UserAddorEditAsync(DreamofMillions.MemberService.UserAddorEditRequest request) {
            return base.Channel.UserAddorEditAsync(request);
        }
        
        public System.Threading.Tasks.Task<DreamofMillions.MemberService.UserAddorEditResponse> UserAddorEditAsync(string FName, string LName, string UserName, string EmailAddress, string Password) {
            DreamofMillions.MemberService.UserAddorEditRequest inValue = new DreamofMillions.MemberService.UserAddorEditRequest();
            inValue.Body = new DreamofMillions.MemberService.UserAddorEditRequestBody();
            inValue.Body.FName = FName;
            inValue.Body.LName = LName;
            inValue.Body.UserName = UserName;
            inValue.Body.EmailAddress = EmailAddress;
            inValue.Body.Password = Password;
            return ((DreamofMillions.MemberService.DreamsWebServiceSoap)(this)).UserAddorEditAsync(inValue);
        }
    }
}
